local env = require("tests.helpers.env")

describe(":Session save", function()
  local sessman

  before_each(function()
    env.setup()
    sessman = env.fresh("sessman")
  end)

  after_each(env.teardown)

  it("needs a name in a plain nvim", function()
    sessman.save()
    assert.matches("argument required", env.echoed[#env.echoed])
  end)

  it("adopts a plain nvim: writes the file and becomes running", function()
    vim.cmd.edit(env.project .. "/a.txt")
    sessman.save("mine")
    local s = sessman.current()
    assert.same({ project = env.project, name = "mine" }, vim.g.sessman_session)
    assert.equals(1, vim.fn.filereadable(s.file))
    assert.matches("a%.txt", table.concat(vim.fn.readfile(s.file), "\n"))
    assert.is_true(vim.tbl_contains(vim.fn.serverlist(), s.sock))
    assert.equals(1, vim.fn.filereadable(s.sock .. ".json"))
    local listed = sessman.resolve("mine", sessman.list())
    assert.is_true(listed.current and listed.running and listed.saved)
  end)

  it("refuses to overwrite an existing session without !", function()
    env.write_session(env.project, "taken", { "original" })
    sessman.save("taken")
    assert.matches("add ! to override", env.echoed[#env.echoed])
    assert.is_nil(vim.g.sessman_session)
    sessman.save("taken", { bang = true })
    assert.are_not.same({ "original" }, vim.fn.readfile(sessman.new(env.project, "taken").file))
  end)

  it("adopts into global: and path targets", function()
    sessman.save("global:notes")
    assert.is_false(sessman.current().project)
  end)

  it("saves the current session in place, but never renames it", function()
    sessman.save("mine")
    sessman.save()
    sessman.save("mine")
    sessman.save("other")
    assert.matches("can't change", env.echoed[#env.echoed])
  end)

  it("writes ShaDa only when asked or already in use", function()
    sessman.save("mine")
    local s = sessman.current()
    assert.equals(0, vim.fn.filereadable(s.shada))
    sessman.save(nil, { shada = true })
    assert.equals(1, vim.fn.filereadable(s.shada))
    assert.equals(s.shada, vim.o.shadafile)
  end)

  it("never records the session buffer, even as the only window", function()
    vim.cmd("runtime plugin/sessman.lua")
    vim.cmd("Session")
    vim.cmd("only")
    assert.equals(1, #vim.api.nvim_list_wins())
    sessman.save("mine")
    local file = table.concat(vim.fn.readfile(sessman.current().file), "\n")
    assert.is_nil(file:find("sessman://", 1, true))
    assert.is_nil(env.find_buf("sessman://sessions"))
  end)

  it("drops a stale sessman:// buffer restored by an old session file", function()
    vim.cmd("enew | file sessman://sessions")
    vim.cmd("split " .. vim.fn.fnameescape(env.project .. "/a.txt"))
    sessman.save("mine")
    local file = table.concat(vim.fn.readfile(sessman.current().file), "\n")
    assert.is_nil(file:find("sessman://", 1, true))
    assert.matches("a%.txt", file)
  end)

  it("closes the session buffer so it isn't recorded", function()
    vim.cmd("runtime plugin/sessman.lua")
    vim.cmd.edit(env.project .. "/a.txt")
    vim.cmd("Session")
    sessman.save("mine")
    assert.is_nil(env.find_buf("sessman://sessions"))
    assert.is_nil(table.concat(vim.fn.readfile(sessman.current().file), "\n"):find("sessman://", 1, true))
  end)
end)
